export const API_URL=import.meta.env.VITE_API_URL??'http://localhost:8080'
export type Role='ADMIN'|'PROFESSIONAL'
export type Session={accessToken:string;userId:string;professionalId:string|null;name:string;role:Role}
export type Professional={id:string;fullName:string;email:string;phone:string|null;registrationNumber:string|null;active:boolean}
export type Patient={id:string;professionalId:string;fullName:string;birthDate:string|null;phone:string;email:string|null;preferredChannel:'WHATSAPP'|'EMAIL';consentStatus:'PENDING'|'GRANTED'|'REVOKED';active:boolean}
export type User={id:string;professionalId:string|null;name:string;email:string;role:Role;active:boolean}
export type AuditLog={id:string;actorUserId:string|null;action:string;resourceType:string;resourceId:string|null;ipAddress:string|null;createdAt:string}
type Page<T>={content:T[];totalElements:number}
async function request<T>(path:string,options:RequestInit={},token?:string):Promise<T>{const response=await fetch(`${API_URL}${path}`,{...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})}});if(!response.ok){const e=await response.json().catch(()=>null);throw new Error(e?.message??`Erro ${response.status}`)}if(response.status===204)return undefined as T;return response.json()}
export const api={login:(email:string,password:string)=>request<Session>('/api/v1/auth/login',{method:'POST',body:JSON.stringify({email,password})}),register:(data:object)=>request<Session>('/api/v1/auth/register',{method:'POST',body:JSON.stringify(data)}),me:(s:Session)=>request<Professional>('/api/v1/professionals/me',{},s.accessToken),updateMe:(s:Session,data:object)=>request<Professional>('/api/v1/professionals/me',{method:'PUT',body:JSON.stringify(data)},s.accessToken),patients:(s:Session)=>request<Page<Patient>>('/api/v1/patients?size=100&sort=fullName,asc',{},s.accessToken),createPatient:(s:Session,data:object)=>request<Patient>('/api/v1/patients',{method:'POST',body:JSON.stringify(data)},s.accessToken),togglePatient:(s:Session,p:Patient)=>request<void>(`/api/v1/patients/${p.id}${p.active?'':'/activate'}`,{method:p.active?'DELETE':'PATCH'},s.accessToken),adminProfessionals:(s:Session)=>request<Page<Professional>>('/api/v1/admin/professionals?size=100&sort=fullName,asc',{},s.accessToken),adminPatients:(s:Session)=>request<Page<Patient>>('/api/v1/admin/patients?size=100&sort=fullName,asc',{},s.accessToken),adminUsers:(s:Session)=>request<Page<User>>('/api/v1/admin/users?size=100&sort=name,asc',{},s.accessToken),adminAudit:(s:Session)=>request<Page<AuditLog>>('/api/v1/admin/audit-logs?size=100&sort=createdAt,desc',{},s.accessToken),toggleUser:(s:Session,u:User)=>request<void>(`/api/v1/admin/users/${u.id}${u.active?'':'/activate'}`,{method:u.active?'DELETE':'PATCH'},s.accessToken),adminUpdateProfessional:(s:Session,p:Professional,data:object)=>request<Professional>(`/api/v1/admin/professionals/${p.id}`,{method:'PUT',body:JSON.stringify(data)},s.accessToken),adminToggleProfessional:(s:Session,p:Professional)=>request<void>(`/api/v1/admin/professionals/${p.id}${p.active?'':'/activate'}`,{method:p.active?'DELETE':'PATCH'},s.accessToken),adminUpdatePatient:(s:Session,p:Patient,data:object)=>request<Patient>(`/api/v1/admin/patients/${p.id}`,{method:'PUT',body:JSON.stringify(data)},s.accessToken),adminTogglePatient:(s:Session,p:Patient)=>request<void>(`/api/v1/admin/patients/${p.id}${p.active?'':'/activate'}`,{method:p.active?'DELETE':'PATCH'},s.accessToken)}
