import { useCallback, useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { api } from './api'
import type { Patient, Session, TenantUser } from './api'
import './App.css'

type View = 'overview' | 'patients' | 'users'

export default function App() {
  const [session, setSession] = useState<Session | null>(() => {
    const saved = localStorage.getItem('consulta-session')
    return saved ? JSON.parse(saved) : null
  })
  if (!session) return <Login onLogin={value => { localStorage.setItem('consulta-session', JSON.stringify(value)); setSession(value) }} />
  return <Dashboard session={session} onLogout={() => { localStorage.removeItem('consulta-session'); setSession(null) }} />
}

function Login({ onLogin }: { onLogin: (value: Session) => void }) {
  const [tenantId, setTenantId] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('')
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(e: FormEvent) { e.preventDefault(); setLoading(true); setError(''); try { onLogin(await api.login(tenantId, email, password)) } catch (r) { setError(r instanceof Error ? r.message : 'Não foi possível entrar') } finally { setLoading(false) } }
  return <main className="login-page"><section className="login-brand"><Logo /><div className="brand-copy"><span className="eyebrow">GESTÃO DE CONSULTAS</span><h1>Menos faltas.<br />Mais cuidado.</h1><p>Organize pacientes e acessos da clínica em um só lugar.</p></div><small>● Ambiente local seguro</small></section><section className="login-panel"><form className="login-card" onSubmit={submit}><span className="mobile-brand">Confirma</span><h2>Bem-vindo de volta</h2><p>Entre com os dados cadastrados na API.</p><label>ID da clínica<input value={tenantId} onChange={e => setTenantId(e.target.value)} placeholder="UUID do tenant" required /></label><label>E-mail<input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="voce@clinica.com" required /></label><label>Senha<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <div className="error">{error}</div>}<button className="primary full" disabled={loading}>{loading ? 'Entrando…' : 'Entrar'}</button><small>Use o mesmo acesso testado no Postman.</small></form></section></main>
}

function Dashboard({ session, onLogout }: { session: Session; onLogout: () => void }) {
  const [view, setView] = useState<View>('overview'); const [patients, setPatients] = useState<Patient[]>([]); const [users, setUsers] = useState<TenantUser[]>([])
  const [error, setError] = useState(''); const [modal, setModal] = useState<'patient' | 'user' | null>(null)
  const load = useCallback(async () => { setError(''); try { setPatients((await api.patients(session)).content); if (session.role !== 'PROFESSIONAL') setUsers((await api.users(session)).content) } catch (r) { setError(r instanceof Error ? r.message : 'Falha ao carregar') } }, [session])
  useEffect(() => { void load() }, [load])
  const title = { overview: 'Visão geral', patients: 'Pacientes', users: 'Usuários' }[view]
  return <div className="app-shell"><aside className="sidebar"><Logo /><nav><Nav active={view === 'overview'} icon="⌂" text="Visão geral" go={() => setView('overview')} /><Nav active={view === 'patients'} icon="♙" text="Pacientes" go={() => setView('patients')} />{session.role !== 'PROFESSIONAL' && <Nav active={view === 'users'} icon="◎" text="Usuários" go={() => setView('users')} />}</nav><div className="sidebar-user"><span className="avatar">{session.name[0]}</span><div><strong>{session.name}</strong><small>{session.role}</small></div></div></aside><main className="content"><header><div><span className="eyebrow">CLÍNICA</span><h1>{title}</h1></div><button className="ghost" onClick={onLogout}>Sair</button></header>{error && <div className="error banner">{error}</div>}{view === 'overview' && <Overview patients={patients} users={users} go={setView} />}{view === 'patients' && <Patients data={patients} editable={session.role !== 'PROFESSIONAL'} add={() => setModal('patient')} toggle={async p => { await api.togglePatient(session, p); await load() }} />}{view === 'users' && <Users data={users} add={() => setModal('user')} toggle={async u => { await api.toggleUser(session, u); await load() }} />}</main>{modal === 'patient' && <PatientModal close={() => setModal(null)} save={async data => { await api.createPatient(session, data); setModal(null); await load() }} />}{modal === 'user' && <UserModal close={() => setModal(null)} save={async data => { await api.createUser(session, data); setModal(null); await load() }} />}</div>
}

function Logo() { return <div className="brand"><span className="brand-mark">C</span><span>Confirma</span></div> }
function Nav({ active, icon, text, go }: { active: boolean; icon: string; text: string; go: () => void }) { return <button className={`nav ${active ? 'active' : ''}`} onClick={go}><span>{icon}</span>{text}</button> }
function Overview({ patients, users, go }: { patients: Patient[]; users: TenantUser[]; go: (v: View) => void }) { return <><section className="stats"><Card label="Pacientes" value={patients.length} detail={`${patients.filter(p => p.active).length} ativos`} /><Card label="Consentimentos" value={patients.filter(p => p.consentStatus === 'GRANTED').length} detail="concedidos" /><Card label="Usuários" value={users.length} detail={`${users.filter(u => u.active).length} ativos`} /></section><section className="welcome"><div><span className="eyebrow">COMECE POR AQUI</span><h2>Sua operação, mais simples.</h2><p>Cadastre pacientes e gerencie os acessos da equipe.</p></div><button className="primary" onClick={() => go('patients')}>Ver pacientes →</button></section><section className="panel"><PanelTitle title="Pacientes recentes" subtitle="Últimos registros disponíveis" /><PatientTable data={patients.slice(0, 5)} /></section></> }
function Card({ label, value, detail }: { label: string; value: number; detail: string }) { return <article><span>{label}</span><strong>{value}</strong><small>{detail}</small></article> }
function PanelTitle({ title, subtitle, action }: { title: string; subtitle: string; action?: React.ReactNode }) { return <div className="panel-title"><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</div> }
function Patients({ data, editable, add, toggle }: { data: Patient[]; editable: boolean; add: () => void; toggle: (p: Patient) => void }) { return <section className="panel"><PanelTitle title="Todos os pacientes" subtitle={`${data.length} registros encontrados`} action={editable && <button className="primary" onClick={add}>+ Novo paciente</button>} /><PatientTable data={data} action={editable ? toggle : undefined} /></section> }
function PatientTable({ data, action }: { data: Patient[]; action?: (p: Patient) => void }) { return <div className="table-wrap"><table><thead><tr><th>Paciente</th><th>Contato</th><th>Canal</th><th>Consentimento</th><th>Status</th>{action && <th />}</tr></thead><tbody>{data.map(p => <tr key={p.id}><td><strong>{p.fullName}</strong><small>{p.birthDate ?? 'Nascimento não informado'}</small></td><td>{p.phone}<small>{p.email ?? 'Sem e-mail'}</small></td><td>{p.preferredChannel}</td><td><Badge value={p.consentStatus} /></td><td><Badge value={p.active ? 'Ativo' : 'Inativo'} /></td>{action && <td><button className="link" onClick={() => action(p)}>{p.active ? 'Desativar' : 'Ativar'}</button></td>}</tr>)}</tbody></table>{!data.length && <Empty text="Nenhum paciente cadastrado." />}</div> }
function Users({ data, add, toggle }: { data: TenantUser[]; add: () => void; toggle: (u: TenantUser) => void }) { return <section className="panel"><PanelTitle title="Equipe e acessos" subtitle={`${data.length} usuários neste tenant`} action={<button className="primary" onClick={add}>+ Novo usuário</button>} /><div className="table-wrap"><table><thead><tr><th>Usuário</th><th>Perfil</th><th>Profissional</th><th>Status</th><th /></tr></thead><tbody>{data.map(u => <tr key={u.id}><td><strong>{u.name}</strong><small>{u.email}</small></td><td><Badge value={u.role} /></td><td>{u.professionalId ? 'Vinculado' : '—'}</td><td><Badge value={u.active ? 'Ativo' : 'Inativo'} /></td><td><button className="link" onClick={() => toggle(u)}>{u.active ? 'Desativar' : 'Ativar'}</button></td></tr>)}</tbody></table>{!data.length && <Empty text="Nenhum usuário cadastrado." />}</div></section> }

function PatientModal({ close, save }: { close: () => void; save: (d: object) => Promise<void> }) { return <DataModal title="Novo paciente" close={close} submit={async f => save(Object.fromEntries(f))}><label className="span">Nome completo<input name="fullName" required /></label><label>Nascimento<input name="birthDate" type="date" /></label><label>Telefone<input name="phone" required /></label><label className="span">E-mail<input name="email" type="email" /></label><label>Canal<select name="preferredChannel"><option>WHATSAPP</option><option>EMAIL</option></select></label></DataModal> }
function UserModal({ close, save }: { close: () => void; save: (d: object) => Promise<void> }) { return <DataModal title="Novo usuário" close={close} submit={async f => { const role = String(f.get('role')); await save({ name: f.get('name'), email: f.get('email'), password: f.get('password'), role, professionalId: role === 'PROFESSIONAL' ? f.get('professionalId') : null }) }}><label className="span">Nome<input name="name" required /></label><label className="span">E-mail<input name="email" type="email" required /></label><label>Senha inicial<input name="password" type="password" minLength={8} required /></label><label>Perfil<select name="role"><option>OWNER</option><option>PROFESSIONAL</option></select></label><label className="span">ID do profissional <i>(para PROFESSIONAL)</i><input name="professionalId" /></label></DataModal> }
function DataModal({ title, close, submit, children }: { title: string; close: () => void; submit: (f: FormData) => Promise<void>; children: React.ReactNode }) { const [error, setError] = useState(''); async function send(e: FormEvent<HTMLFormElement>) { e.preventDefault(); try { await submit(new FormData(e.currentTarget)) } catch (r) { setError(r instanceof Error ? r.message : 'Erro ao salvar') } } return <div className="modal-backdrop" onMouseDown={close}><section className="modal" onMouseDown={e => e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button onClick={close}>×</button></div><form className="form-grid" onSubmit={send}>{children}{error && <div className="error span">{error}</div>}<div className="form-actions span"><button type="button" className="ghost" onClick={close}>Cancelar</button><button className="primary">Salvar</button></div></form></section></div> }
function Badge({ value }: { value: string }) { return <span className={`badge ${value.toLowerCase()}`}>{value}</span> }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div> }
