import {useCallback, useEffect, useRef, useState} from 'react';
import type {FormEvent} from 'react';
import {api, type Appointment, type Patient, type Professional, type ScheduleBlock, type Session} from './api';
import './Sessions.css';
import './SessionsBusinessHours.css';

const statusLabels = {SCHEDULED:'Agendada', CONFIRMED:'Confirmada', COMPLETED:'Realizada', CANCELED:'Cancelada', NO_SHOW:'Não compareceu'};
const START_HOUR=0, END_HOUR=24, HOUR_HEIGHT=56;
const hours=Array.from({length:END_HOUR-START_HOUR},(_,i)=>START_HOUR+i);

function monday(date:Date){const d=new Date(date);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}
function addDays(date:Date,n:number){const d=new Date(date);d.setDate(d.getDate()+n);return d}
function localValue(value:Date|string){const d=new Date(value),offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,16)}
function dateValue(value:Date){return localValue(value).slice(0,10)}
export function layoutAppointments(items:Appointment[]){const result:{item:Appointment;column:number;columns:number}[]=[];let group:Appointment[]=[],groupEnd=-Infinity;const flush=()=>{const ends:number[]=[];const positioned=group.map(item=>{const start=new Date(item.startsAt).getTime(),end=new Date(item.endsAt).getTime();let column=ends.findIndex(value=>value<=start);if(column<0){column=ends.length;ends.push(end)}else ends[column]=end;return{item,column}});result.push(...positioned.map(entry=>({...entry,columns:ends.length})));group=[];groupEnd=-Infinity};for(const item of items.slice().sort((a,b)=>new Date(a.startsAt).getTime()-new Date(b.startsAt).getTime())){const start=new Date(item.startsAt).getTime(),end=new Date(item.endsAt).getTime();if(group.length&&start>=groupEnd)flush();group.push(item);groupEnd=Math.max(groupEnd,end)}flush();return result}

export function SessionsView({session,patients,professional,initialPatientId,openNewSession,onInitialPatientHandled}:{session:Session;patients:Patient[];professional?:Professional;initialPatientId?:string;openNewSession?:boolean;onInitialPatientHandled?:()=>void}){
  const [week,setWeek]=useState(()=>monday(new Date()));
  const [items,setItems]=useState<Appointment[]>([]);
  const [blocks,setBlocks]=useState<ScheduleBlock[]>([]);
  const [view,setView]=useState<'CALENDAR'|'LIST'>('CALENDAR');
  const [listStart,setListStart]=useState(()=>dateValue(monday(new Date())));
  const [listEnd,setListEnd]=useState(()=>dateValue(addDays(monday(new Date()),6)));
  const [listItems,setListItems]=useState<Appointment[]>([]);
  const [listPatientId,setListPatientId]=useState('');
  const [listStatus,setListStatus]=useState('');
  const [listPage,setListPage]=useState(0);
  const [listLoading,setListLoading]=useState(false);
  const [editing,setEditing]=useState<Appointment|null>(null);
  const [draft,setDraft]=useState<Date|null>(null);
  const [blockDraft,setBlockDraft]=useState<Date|null>(null);
  const [draftPatientId,setDraftPatientId]=useState<string|undefined>();
  const [error,setError]=useState('');
  const [now,setNow]=useState(()=>new Date());
  const calendarRef=useRef<HTMLDivElement>(null);
  const days=Array.from({length:7},(_,i)=>addDays(week,i)),end=addDays(week,7);
  const load=useCallback(async()=>{try{setError('');const [appointments,scheduleBlocks]=await Promise.all([api.sessions(session,week.toISOString(),end.toISOString()),api.scheduleBlocks(session,week.toISOString(),end.toISOString())]);setItems(appointments);setBlocks(scheduleBlocks)}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar as sessões')}},[session,week]);
  const loadList=useCallback(async()=>{if(!listStart||!listEnd||listStart>listEnd)return;try{setError('');setListLoading(true);const until=addDays(new Date(`${listEnd}T12:00:00`),1);setListItems(await api.sessions(session,new Date(`${listStart}T00:00:00`).toISOString(),until.toISOString()))}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar as sessões')}finally{setListLoading(false)}},[session,listStart,listEnd]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(view==='LIST')void loadList()},[view,loadList]);
  useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date()),60000);return()=>window.clearInterval(timer)},[]);
  useEffect(()=>{if(calendarRef.current)calendarRef.current.scrollTop=8*HOUR_HEIGHT},[]);

  function openSlot(day:Date,hour:number){
    const date=new Date(day);date.setHours(hour,0,0,0);
    if(date.getTime()<Date.now()){setError('Não é possível agendar uma sessão em um horário que já passou.');return}
    setError('');setDraft(date);
  }
  function openNext(){
    const date=new Date();date.setMinutes(0,0,0);date.setHours(date.getHours()+1);
    if(date.getHours()>=END_HOUR){date.setDate(date.getDate()+1);date.setHours(9)}
    openSlot(date,date.getHours());
  }
  function openBlock(){const date=new Date();date.setMinutes(0,0,0);date.setHours(date.getHours()+1);if(date.getHours()>=END_HOUR){date.setDate(date.getDate()+1);date.setHours(9)}setError('');setBlockDraft(date)}
  useEffect(()=>{if(initialPatientId||openNewSession){setDraftPatientId(initialPatientId);openNext();onInitialPatientHandled?.()}},[initialPatientId,openNewSession,onInitialPatientHandled]);

  const period=`${week.toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})} — ${addDays(week,6).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'})}`;
  const nowMinutes=now.getHours()*60+now.getMinutes(),lineTop=(nowMinutes-START_HOUR*60)/60*HOUR_HEIGHT;
  const showCurrentLine=now>=week&&now<end&&lineTop>=0&&lineTop<=(END_HOUR-START_HOUR)*HOUR_HEIGHT;
  const filteredList=listItems.filter(item=>(!listPatientId||item.patientId===listPatientId)&&(!listStatus||item.status===listStatus)).sort((a,b)=>new Date(a.startsAt).getTime()-new Date(b.startsAt).getTime());
  const pageSize=15,pageCount=Math.max(1,Math.ceil(filteredList.length/pageSize)),page=Math.min(listPage,pageCount-1),pageItems=filteredList.slice(page*pageSize,(page+1)*pageSize);
  function refresh(){void load();if(view==='LIST')void loadList()}
  async function removeBlock(block:ScheduleBlock){if(!window.confirm(`Remover o bloqueio${block.reason?` “${block.reason}”`:''}?`))return;try{setError('');await api.deleteScheduleBlock(session,block.id);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível remover o bloqueio')}}
  return <>
    <section className="sessions-panel">
      <div className="sessions-toolbar">
        <div>{view==='CALENDAR'?<><label className="week-picker"><span>{period}</span><input aria-label="Selecionar semana" type="date" value={localValue(week).slice(0,10)} onChange={e=>{if(e.target.value)setWeek(monday(new Date(`${e.target.value}T12:00:00`)))}}/></label><p>Visão semanal da sua agenda</p></>:<><h2>Lista de sessões</h2><p>Consulte sessões por período, paciente ou status</p></>}</div>
        <div>{view==='CALENDAR'&&<><button className="ghost" onClick={()=>setWeek(addDays(week,-7))}>‹</button><button className="ghost" onClick={()=>setWeek(monday(new Date()))}>Hoje</button><button className="ghost" onClick={()=>setWeek(addDays(week,7))}>›</button><button className="ghost" onClick={openBlock}>Bloquear horário</button></>}<button className="primary" onClick={openNext}>+ Nova sessão</button></div>
      </div>
      <div className="sessions-view-toggle" role="group" aria-label="Visualização das sessões"><button className={view==='CALENDAR'?'selected':''} onClick={()=>setView('CALENDAR')}>Agenda semanal</button><button className={view==='LIST'?'selected':''} onClick={()=>setView('LIST')}>Lista de sessões</button></div>
      {error&&<div className="error banner">{error}</div>}
      {view==='CALENDAR'?<div className="calendar-scroll" ref={calendarRef}>
        <div className="calendar-header"><div className="time-corner"/>{days.map(day=>{const current=day.toDateString()===new Date().toDateString();return <button className={`day-head ${current?'today':''}`} key={day.toISOString()} onClick={()=>openSlot(day,9)}><span>{day.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')}</span><strong>{day.getDate()}</strong></button>})}</div>
        <div className="calendar-body">
          {showCurrentLine&&<div className="current-time-line" style={{top:lineTop}}><span/></div>}
          <div className="time-gutter">{hours.map(hour=><span key={hour} style={{top:(hour-START_HOUR)*HOUR_HEIGHT+4}}>{String(hour).padStart(2,'0')}:00</span>)}</div>
          <div className="calendar-days">{days.map(day=>{
            const current=day.toDateString()===new Date().toDateString(),dayItems=layoutAppointments(items.filter(item=>new Date(item.startsAt).toDateString()===day.toDateString())),dayBlocks=blocks.filter(block=>new Date(block.startsAt).toDateString()===day.toDateString());
            return <div className={`calendar-day ${current?'today':''}`} key={day.toISOString()} style={{height:(END_HOUR-START_HOUR)*HOUR_HEIGHT}}>
              {hours.map(hour=>{const slot=new Date(day),slotEnd=new Date(day);slot.setHours(hour,0,0,0);slotEnd.setHours(hour+1,0,0,0);const past=slot.getTime()<Date.now(),blocked=dayBlocks.some(block=>new Date(block.startsAt)<slotEnd&&new Date(block.endsAt)>slot);return <button disabled={past||blocked} aria-label={blocked?'Horário bloqueado':`Criar sessão às ${hour}:00`} className={`hour-slot ${hour>=8&&hour<18?'business-hour':''} ${past?'past':''} ${blocked?'blocked':''}`} key={hour} onClick={()=>openSlot(day,hour)} style={{top:(hour-START_HOUR)*HOUR_HEIGHT,height:HOUR_HEIGHT}}/>})}
              {dayBlocks.map(block=>{const start=new Date(block.startsAt),finish=new Date(block.endsAt),startMinutes=start.getHours()*60+start.getMinutes(),endMinutes=finish.getHours()*60+finish.getMinutes(),top=Math.max(0,(startMinutes-START_HOUR*60)/60*HOUR_HEIGHT),height=Math.max(30,(endMinutes-startMinutes)/60*HOUR_HEIGHT);return <button key={block.id} title="Clique para remover o bloqueio" className="schedule-block" onClick={()=>void removeBlock(block)} style={{top,height}}><time>{start.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}–{finish.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time><strong>{block.reason||'Horário bloqueado'}</strong></button>})}
              {dayItems.map(({item,column,columns})=>{const start=new Date(item.startsAt),finish=new Date(item.endsAt),startMinutes=start.getHours()*60+start.getMinutes(),endMinutes=finish.getHours()*60+finish.getMinutes(),top=Math.max(0,(startMinutes-START_HOUR*60)/60*HOUR_HEIGHT),height=Math.max(30,(endMinutes-startMinutes)/60*HOUR_HEIGHT),tooltip=item.notes?`Observação: ${item.notes}`:undefined;return <button key={item.id} title={tooltip} style={{top,height,left:`calc(4px + ${column} * ((100% - 8px) / ${columns}))`,width:`calc((100% - 8px) / ${columns})`,right:'auto'}} className={`session-card ${item.status.toLowerCase()}`} onClick={()=>setEditing(item)}><time>{start.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}–{finish.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}{item.notes&&<span className="note-indicator" aria-label="Possui observação"> ●</span>}</time><strong>{item.patientName}</strong><small>{statusLabels[item.status]} · {item.modality==='ONLINE'?'Online':'Presencial'}</small></button>})}
            </div>})}</div>
        </div>
      </div>:<div className="sessions-list"><div className="sessions-filters"><label>De<input type="date" value={listStart} onChange={e=>{setListStart(e.target.value);setListPage(0)}}/></label><label>Até<input type="date" value={listEnd} min={listStart} onChange={e=>{setListEnd(e.target.value);setListPage(0)}}/></label><label>Paciente<select value={listPatientId} onChange={e=>{setListPatientId(e.target.value);setListPage(0)}}><option value="">Todos os pacientes</option>{patients.map(p=><option key={p.id} value={p.id}>{p.fullName}</option>)}</select></label><label>Status<select value={listStatus} onChange={e=>{setListStatus(e.target.value);setListPage(0)}}><option value="">Todos os status</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>{listLoading?<p className="sessions-list-empty">Carregando sessões…</p>:pageItems.length?<><div className="sessions-list-table">{pageItems.map(item=>{const start=new Date(item.startsAt),finish=new Date(item.endsAt);return <button key={item.id} className="sessions-list-row" onClick={()=>setEditing(item)}><time>{start.toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'})}<strong>{start.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}–{finish.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</strong></time><span><strong>{item.patientName}</strong><small>{item.modality==='ONLINE'?'Online':'Presencial'}</small></span><em className={`session-status ${item.status.toLowerCase()}`}>{statusLabels[item.status]}</em></button>})}</div><div className="sessions-pagination"><span>Mostrando {page*pageSize+1}–{Math.min((page+1)*pageSize,filteredList.length)} de {filteredList.length}</span><div><button className="ghost" disabled={page===0} onClick={()=>setListPage(page-1)}>Anterior</button><button className="ghost" disabled={page>=pageCount-1} onClick={()=>setListPage(page+1)}>Próxima</button></div></div></>:<p className="sessions-list-empty">Nenhuma sessão encontrada nesse período.</p>}</div>}
    </section>
    {(editing||draft)&&<SessionModal item={editing} initial={draft} patientId={draftPatientId} patients={patients.filter(p=>p.active)} defaultDuration={professional?.defaultSessionMinutes??60} defaultModality={professional?.defaultModality??'PRESENTIAL'} close={()=>{setEditing(null);setDraft(null);setDraftPatientId(undefined)}} save={async data=>{if(editing)await api.updateSession(session,editing.id,data);else await api.createSession(session,data);setEditing(null);setDraft(null);setDraftPatientId(undefined);refresh()}} cancel={editing?async()=>{await api.updateSession(session,editing.id,{patientId:editing.patientId,startsAt:editing.startsAt,endsAt:editing.endsAt,modality:editing.modality,status:'CANCELED',meetingLink:editing.meetingLink,notes:editing.notes});setEditing(null);refresh()}:undefined}/>}
    {blockDraft&&<ScheduleBlockModal initial={blockDraft} close={()=>setBlockDraft(null)} save={async data=>{await api.createScheduleBlock(session,data);setBlockDraft(null);await load()}}/>}
  </>
}

function SessionModal({item,initial,patientId,patients,defaultDuration,defaultModality,close,save,cancel}:{item:Appointment|null;initial:Date|null;patientId?:string;patients:Patient[];defaultDuration:number;defaultModality:'PRESENTIAL'|'ONLINE';close:()=>void;save:(data:object)=>Promise<void>;cancel?:()=>Promise<void>}){
  const[error,setError]=useState(''),[busy,setBusy]=useState(false),[rescheduling,setRescheduling]=useState(false),start=item?.startsAt??initial??new Date(),finish=item?.endsAt??new Date(new Date(start).getTime()+defaultDuration*60000);
  if(item && (new Date(item.endsAt).getTime()<=Date.now() || item.status==='CANCELED' || item.status==='COMPLETED' || item.status==='NO_SHOW'))return <div className="modal-backdrop"><section className="modal"><div className="modal-head"><h2>Detalhes da sessão</h2><button type="button" onClick={close} aria-label="Fechar">×</button></div><div className="session-readonly"><p>Esta sessão está disponível apenas para consulta. Se o status estiver pendente, atualize-o no histórico do paciente.</p><dl><div><dt>Paciente</dt><dd>{item.patientName}</dd></div><div><dt>Início</dt><dd>{new Date(item.startsAt).toLocaleString('pt-BR')}</dd></div><div><dt>Término</dt><dd>{new Date(item.endsAt).toLocaleString('pt-BR')}</dd></div><div><dt>Modalidade</dt><dd>{item.modality==='ONLINE'?'Online':'Presencial'}</dd></div><div><dt>Status</dt><dd>{statusLabels[item.status]}</dd></div><div><dt>Link da sessão</dt><dd>{item.meetingLink||'—'}</dd></div><div><dt>Observação</dt><dd>{item.notes||'—'}</dd></div></dl><div className="form-actions"><button type="button" className="primary" onClick={close}>Fechar</button></div></div></section></div>;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const f=new FormData(event.currentTarget);try{await save({patientId:f.get('patientId'),startsAt:new Date(String(f.get('startsAt'))).toISOString(),endsAt:new Date(String(f.get('endsAt'))).toISOString(),modality:f.get('modality'),status:f.get('status'),meetingLink:f.get('meetingLink')||null,notes:f.get('notes')||null})}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar a sessão');setBusy(false)}}
  const formActions=<div className="form-actions span"><button type="button" className="ghost" onClick={rescheduling?()=>setRescheduling(false):close}>{rescheduling?'Voltar':'Fechar sem salvar'}</button><button className="primary" disabled={busy}>{busy?(rescheduling?'Reagendando…':'Salvando…'):(rescheduling?'Confirmar reagendamento':'Salvar sessão')}</button></div>;
  if(rescheduling&&item)return <div className="modal-backdrop"><section className="modal"><div className="modal-head"><h2>Reagendar sessão</h2><button onClick={close}>×</button></div><form className="form-grid" onSubmit={submit}><div className="reschedule-summary span"><strong>{item.patientName}</strong><span>{item.modality==='ONLINE'?'Online':'Presencial'} · {statusLabels[item.status]}</span></div><input type="hidden" name="patientId" value={item.patientId}/><input type="hidden" name="modality" value={item.modality}/><input type="hidden" name="status" value={item.status}/><input type="hidden" name="meetingLink" value={item.meetingLink??''}/><input type="hidden" name="notes" value={item.notes??''}/><label>Nova data e horário<input name="startsAt" type="datetime-local" min={localValue(new Date())} defaultValue={localValue(start)} required/></label><label>Novo término<input name="endsAt" type="datetime-local" defaultValue={localValue(finish)} required/></label><p className="span field-hint">Os demais dados e o status da sessão serão mantidos.</p>{error&&<div className="error span">{error}</div>}{formActions}</form></section></div>;
  return <div className="modal-backdrop"><section className="modal"><div className="modal-head"><h2>{item?'Editar sessão':'Nova sessão'}</h2><button onClick={close}>×</button></div><form className="form-grid" onSubmit={submit}><label className="span">Paciente<select name="patientId" defaultValue={item?.patientId??patientId} required><option value="">Selecione</option>{patients.map(p=><option key={p.id} value={p.id}>{p.fullName}</option>)}</select></label><label>Início<input name="startsAt" type="datetime-local" min={item?undefined:localValue(new Date())} defaultValue={localValue(start)} required/></label><label>Término<input name="endsAt" type="datetime-local" defaultValue={localValue(finish)} required/></label><label>Modalidade<select name="modality" defaultValue={item?.modality??defaultModality}><option value="PRESENTIAL">Presencial</option><option value="ONLINE">Online</option></select></label>{item?<label>Status<select name="status" defaultValue={item.status}><option value="SCHEDULED">Agendada</option><option value="CONFIRMED">Confirmada</option></select></label>:<input type="hidden" name="status" value="SCHEDULED"/>}<label className="span">Link da sessão (opcional)<input name="meetingLink" type="url" defaultValue={item?.meetingLink??''} maxLength={500}/></label><label className="span">Observação (opcional)<input name="notes" defaultValue={item?.notes??''} maxLength={500}/></label>{error&&<div className="error span">{error}</div>}{item&&<div className="span session-secondary-actions"><button type="button" className="link" onClick={()=>{setError('');setRescheduling(true)}}>Reagendar sessão</button>{cancel&&<button type="button" className="link danger-link" disabled={busy} onClick={async()=>{if(!window.confirm(`Cancelar a sessão de ${item.patientName}?`))return;setBusy(true);setError('');try{await cancel()}catch(e){setError(e instanceof Error?e.message:'Não foi possível cancelar a sessão');setBusy(false)}}}>Cancelar sessão</button>}</div>}{formActions}</form></section></div>
}

function ScheduleBlockModal({initial,close,save}:{initial:Date;close:()=>void;save:(data:object)=>Promise<void>}){
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const finish=new Date(initial.getTime()+60*60000);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);try{await save({startsAt:new Date(String(form.get('startsAt'))).toISOString(),endsAt:new Date(String(form.get('endsAt'))).toISOString(),reason:form.get('reason')||null})}catch(e){setError(e instanceof Error?e.message:'Não foi possível bloquear o horário');setBusy(false)}}
  return <div className="modal-backdrop"><section className="modal"><div className="modal-head"><h2>Bloquear horário</h2><button onClick={close}>×</button></div><form className="form-grid" onSubmit={submit}><p className="span field-hint">Use para indisponibilidades, pausas ou compromissos pessoais.</p><label>Início<input name="startsAt" type="datetime-local" min={localValue(new Date())} defaultValue={localValue(initial)} required/></label><label>Término<input name="endsAt" type="datetime-local" defaultValue={localValue(finish)} required/></label><label className="span">Motivo (opcional)<input name="reason" maxLength={500} placeholder="Ex.: almoço, férias ou reunião"/></label>{error&&<div className="error span">{error}</div>}<div className="form-actions span"><button type="button" className="ghost" onClick={close}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Bloqueando…':'Bloquear horário'}</button></div></form></section></div>
}
